### ISSUE TITLE
Space before self closing tags

### ISSUE THREAD

**Issue by pxwee5** [Prettyhtml/prettyhtml#80]
## 🚀 Feature Proposal
Align with Vue's style guide

## Motivation
https://github.com/vuejs/eslint-plugin-vue/blob/master/docs/rules/html-closing-bracket-spacing.md

## Example
In
```
<my-component name="test"/>
```

out
```
<my-component name="test" />
```

Note the space before the self closing tag.

**Comment by StarpTech** [comment]
Hi @pxwee5 thank you for the proposal. According to the eslint rule you can set it to `never`.

**Comment by sam3d** [comment]
@StarpTech Would you accept a PR changes the formatting to add a space before the self closing tag? This is standard best practice and is the way the current default prettier implementation works.

**Comment by sam3d** [comment]
Good to know, thank you!

And I will do when I get a moment.

**Comment by sam3d** [comment]
Sorry I haven't had any time to get to this; my team and I just decided to just use prettier's default formatting for HTML (despite my gripes with it) because it's easier for us to adopt globally and supports self-closing tags for vue by default.

@StarpTech I apologise I don't think I'll have time to work on a PR for this in the near future :(

**Comment by jongio** [comment]
@sam3d - When you have time, could you share the ES Lint rules you use with Prettier to allow no space on self-closing tag?
